---
- name: Run Linux collection
  import_tasks: collections/ansible_collections/apidb/apidb_collection/roles/apidb_localfacts/tasks/linux.yml
  when: ansible_os_family != "Windows"

######
# Reservers for future use.
#- name: Run Windows collection
#  import_tasks: collections/ansible_collections/apidb/apidb_collection/roles/apidb_localfacts/tasks/windows.yml
#  when: ansible_os_family == "Windows"
#####
