---
- name: remove any previous facts
  file:
    path: /tmp/local/kubernetes_files
    state: absent

- name: remove any previous facts
  file:
    path: /tmp/kubernetes_files
    state: absent

- name: create temporary local fact home
  shell: |
    mkdir -p /tmp/kubernetes_files/$(kubectl config current-context --kubeconfig="{{ item }}"| awk -F@ '{print $2}')
    kubectl cluster-info dump --all-namespaces --kubeconfig="{{ item }}" --output-directory=/tmp/cluster-state --insecure-skip-tls-verify
    for i in `find /tmp/cluster-state -name \*.json -type f`; do cp $i /tmp/kubernetes_files/$(kubectl config current-context --kubeconfig="{{ item }}"| awk -F@ '{print $2}')/$(echo $i |sed 's:/:.:g' | sed  's/^/''/'); done
    kubectl config view --kubeconfig="$HOME/.kube/test-cluster.yml" -o json > /tmp/kubernetes_files/$(kubectl config current-context --kubeconfig="{{ item }}"| awk -F@ '{print $2}')/.cluster-info.json
    rm /tmp/kubernetes_files/$(kubectl config current-context --kubeconfig="{{ item }}"| awk -F@ '{print $2}')/.*.kube-*
    rm -fr /tmp/cluster-state
  args:
    warn: no
  loop: "{{ kubeconfig }}"

