---
# tasks file for apidb-collect

- name: Create custom fact directory
  file:
    path: /tmp/facts
    state: directory
  delegate_to: localhost

- name: Add facts to a variable
  setup:
    fact_path: /tmp/local
  register: setupvar

- name: Store facts indexed by hostname in /tmp/facts
  copy:
    content: '{{ setupvar }}'
    dest: /tmp/facts/{{ ansible_hostname }}.yaml
    mode: 0600
  delegate_to: localhost
