---
- name: Run Linux collection
  import_tasks: collections/ansible_collections/apidb/apidb_collection/roles/apidb_collect/tasks/linux.yml
  when: ansible_os_family != "Windows"

- name: Run Windows collection
  import_tasks: collections/ansible_collections/apidb/apidb_collection/roles/apidb_collect/tasks/windows.yml
  when: ansible_os_family == "Windows"
